#!/bin/bash

cd "`dirname $0`"
path="`pwd`"
ln -s "$path/gitattributes" ~/.gitattributes
ln -s "$path/gitexcludes" ~/.gitexcludes
ln -s "$path/gitconfig" ~/.gitconfig
ln -s "$path/bash_profile" ~/.bash_profile
ln -s "$path/zshrc" ~/.zshrc
ln -s "$path/vimrc" ~/.vimrc
